title: Ricky Taki
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ricky Taki # add your name
author-img: ricky-taki.jpg # add your photo
about-author: I am a Java developer and Digital Marketing enthusiast. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rickytaki # add your Github handle
social-linkedin: ricardotaki # add your Linkedin handle
social-email: me@rickytaki.com # add your Email address

# Disqus
discus-identifier: rickytaki # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
